version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4   # (1)
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Build version
          command: echo export BUILD_DATE=`date +"v%Y%m%d_%H%M%S"` >> $BASH_ENV
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker build
          command: |
            echo "Building tag $BUILD_DATE..."
            docker build --rm --no-cache -t "$DOCKER_USER"/bitrise-android-ndk-trimmed .
            docker tag "$DOCKER_USER"/bitrise-android-ndk-trimmed "$DOCKER_USER"/bitrise-android-ndk-trimmed:"$BUILD_DATE"
      - run:
          name: Docker push
          command: |
            echo "Pushing tag $BUILD_DATE..."
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "$DOCKER_USER"/bitrise-android-ndk-trimmed
            docker push "$DOCKER_USER"/bitrise-android-ndk-trimmed:"$BUILD_DATE"
